#pragma once

#include <cstdint>
#include <d3d12.h>

namespace kt::rdr {
  using ImageFormat = DXGI_FORMAT;
  using ImageLayout = D3D12_RESOURCE_STATES;

  constexpr ImageFormat KT_FORMAT_UNDEFINED = DXGI_FORMAT_UNKNOWN;

  constexpr ImageLayout KT_IMAGE_LAYOUT_UNDEFINED = D3D12_RESOURCE_STATE_COMMON;
  constexpr ImageLayout KT_IMAGE_LAYOUT_SHADER_READ =
      D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE | D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
  constexpr ImageLayout KT_IMAGE_LAYOUT_SHADER_STORAGE_READ_WRITE = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
  constexpr ImageLayout KT_IMAGE_LAYOUT_COLOR_ATTACHMENT = D3D12_RESOURCE_STATE_RENDER_TARGET;
  constexpr ImageLayout KT_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT = D3D12_RESOURCE_STATE_DEPTH_WRITE;
  constexpr ImageLayout KT_IMAGE_LAYOUT_SHADER_READ_ATTACHMENT =
      D3D12_RESOURCE_STATE_RENDER_TARGET | D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE;
  constexpr ImageLayout KT_IMAGE_LAYOUT_SHADER_READ_DEPTH_ATTACHMENT =
      D3D12_RESOURCE_STATE_DEPTH_WRITE | D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE;
  constexpr ImageLayout KT_IMAGE_LAYOUT_SHADER_READ_DEPTH_READ_ATTACHMENT =
      D3D12_RESOURCE_STATE_DEPTH_READ | D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE;

  enum class DescriptorType : uint8_t {
    None,
    ConstantBuffer,
    ShaderResource,
    UnorderedAccess,
  };
} // namespace kt::rdr
